version: "3.8"

services:
  backend:
    image: registry.gitlab.com/arpandaze/sikshyalaya/backend:latest
    container_name: backend
    environment:
      - CONFIG_PATH=etc/dock.yml
    depends_on:
      - postgres
      - redis
    networks:
      - internal
    ports:
      - "8080:80"
    volumes:
      - ./.files:/file_server

  web:
    image: registry.gitlab.com/arpandaze/sikshyalaya/web:latest
    container_name: web
    ports:
      - "3001:80"

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    networks:
      - internal
    volumes:
      - persistent:/var/lib/postgres/data
    environment:
      - PGDATA=/var/lib/postgres/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    links:
      - postgres:postgres
    networks:
      - internal
    depends_on:
      - postgres
    ports:
      - "5050:80"
    logging:
      driver: none

  redis:
    image: redis:6-alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - internal
    ports:
      - "6379:6379"

  file_server:
    image: registry.gitlab.com/arpandaze/sikshyalaya/file_server:latest
    container_name: file_server
    networks:
      - internal
    volumes:
      - ./.files:/content/
    ports:
      - "8081:80"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    networks:
      - internal
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  persistent:

networks:
  internal:
    driver: bridge
