version: "2.1"

jobs:
  build:
    docker:
      - image: docker/compose

    working_directory: /app

    steps:
      - checkout

      # Set up Docker Compose services
      - run:
          name: Start Docker Compose services
          command: docker-compose up -d

      # Run your tests or build steps here
      # For example, you can add the following lines to run tests with pytest:
      # - run:
      #     name: Run tests
      #     command: docker-compose exec backend pytest

      # Additional build steps, if needed

      # Stop Docker Compose services after the build
      - run:
          name: Stop Docker Compose services
          command: docker-compose down

workflows:
  version: 2
  build_workflow:
    jobs:
      - build
