version: 2.1

jobs:
  build:
    docker:
      - image: docker/compose:1.29.2

    working_directory: /app

    steps:
      - setup_remote_docker  # Enable Docker within CircleCI

      - checkout

      # Set up Docker Compose services
      - run:
          name: Start Docker Compose services
          command: docker-compose up -d
              # Stop Docker Compose services after the build
      - run:
          name: Stop Docker Compose services
          command: docker-compose down

      # Run your tests or build steps here
      - run:  
          name: Install dependencies  
          command: |  
            pip install -r backend/requirements.txt  
  
      - run:  
          name: Run pytest  
          command: |  
            pytest  
  



workflows:
  version: 2
  build_workflow:
    jobs:
      - build
