jobs:
  build:
    docker:
      - image: docker/compose:1.29.2

    working_directory: /app

    steps:
      - setup_remote_docker  # Enable Docker within CircleCI

      - checkout


      # Run your tests or build steps here
      - run:  
          name: Install Python and pip  
          command: |  
            apk update
            apk add python3 py3-pip
      - run:  
          name: Install dependencies  
          command: |  
            cd backend
            sudo apt-get install gcc python3-dev musl-dev
            pip3 install -r requirements.txt  
            python3 manage.py pytest
  

workflows:
  version: 2
  build_workflow:
    jobs:
      - build
