version: 2.1
jobs:
  test-backend:
    docker:
      - image: python:latest

    environment:
      POSTGRES_DB: "sikshyalaya"
      POSTGRES_USER: "postadmin"
      POSTGRES_PASSWORD: "postpass"
      CONFIG_PATH: "etc/dock.yml"
      REDIS_HOST: redis

    steps:
      - checkout

      - run:
          name: Install Poetry
          command: |
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
            source $HOME/.poetry/env

      - run:
          name: Install Dependencies
          command: |
            cd backend
            poetry config virtualenvs.create false
            poetry install --no-dev

      - run:
          name: Run Tests
          command: |
            cd backend
            python manage.py remake
            python manage.py pytest

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - test-backend:
          filters:
            branches:
              only: main
