version: 2.1
jobs:
  testbackend:
    docker:
      - image: cimg/python:3.10
        environment:
          POSTGRES_DB: sikshyalaya
          POSTGRES_USER: postadmina
          POSTGRES_PASSWORD: postpass
          CONFIG_PATH: etc/dock.yml
          REDIS_HOST: redis
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y curl
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
            source $HOME/.poetry/env
            cd backend && poetry config virtualenvs.create false && poetry install --no-dev
      - run:
          name: Run tests
          command: |
            python manage.py remake
            python manage.py pytest

workflows:
  version: 2
  pipeline:
    jobs:
      - testbackend
