version: 2.1

jobs:
  build:
    docker:
      - image: docker/compose:1.29.2

    working_directory: /app

    steps:
      - setup_remote_docker  # Enable Docker within CircleCI

      - checkout

      # Set up Docker Compose services
      - run:
          name: Start Docker Compose services
          command: docker-compose up -d

      # Run your tests or build steps here
      # For example, you can add the following lines to run tests with pytest:
      - run:
          name: Run tests
          command: |
            export _JAVA_OPTIONS="-Xmx3g"
            docker-compose exec backend pytest tests

      # Additional build steps, if needed

      # Stop Docker Compose services after the build
      - run:
          name: Stop Docker Compose services
          command: docker-compose down

workflows:
  version: 2
  build_workflow:
    jobs:
      - build
